### ISSUE TITLE
Change Survey Seeder file

### ISSUE THREAD

**Issue by mah-shamim** [hafijul233/bbs-nsds#9]
maintain this sequence 
--------------------------------------
Cost of Migration Survey 
Distributive Trade Survey
Hotel and Restaurant survey 
Household Income and Expenditure Survey 
Improvement of GDP Compilation and Rebasing of Indices
Improving Labour Market Information through Labour Force Survey (LFS) 
Measuring ICT Access and Use by Households and Individuals 
Multiple Indicator Cluster Survey (MICS) 
National Hygiene survey
National Survey on Persons with Disabilities
Pilot Survey on SADDD and CCA & DRR
Report on Sample Vital Registration System (SVRS)
Report on the Survey of Private Healthcare Institutions
Strengthening of Environment, Climate Change and Disaster Related Statistics 
Survey of Manufacturing Industries (SMI) 
Survey of Travel Agent, Tour Operator and Clearing & Forwarding Agent 
Survey on Gross Marketed Surplus of Agricultural Commodities
Survey on Private Commercial Mechanized and Non-Mechanized and Water Transport 
Survey on Private Health Service Establishment
Time Use Survey 
Tourism Satellite Account
Urban Socioeconomic Assessment Survey 
Urban Socioeconomic Assessment Survey Determination of Causes of Deaths by Verbal Autopsy (VA) Perception Survey on Livelihood (PSL)
User Satisfaction Survey
Wholesale and Retail Trade Survey

**Comment by mah-shamim** [comment]
done

**Comment by hafijul233** [comment]
merged
